### ISSUE TITLE
build with string values

### ISSUE THREAD

**Issue by muayyad-alsadi** [muayyad-alsadi/podman-compose#10]
as seen [here](https://docs.docker.com/compose/overview/) build might have a string value

```
version: '3'
services:
  web:
    build: .
```

which is to be interpreted as 

```
version: '3'
services:
  web:
    build:
      context: .
```
