### ISSUE TITLE
[question] best way to run multiple instances of x?

### ISSUE THREAD

**Issue by chpio** [muayyad-alsadi/podman-compose#14]
Hi,

im running multiple instances of mysql/mariadb on the default port in docker-compose, what is the best way to run them in podman-compose? Do i need to change the ports, because podman is not able to give each container a  separated ip?

**Comment by muayyad-alsadi** [comment]
same problem would happen if you have multiple redis/mongo replicas ..etc.
and yes, you need to customize ports, unfortunately this is not easy for example in mysql you need to edit `/etc/my.cnf` but in `redis` you can pass `--port 7777`, like this

```
version: '3'
services:
  redis:
    read_only: true
    image: redis:alpine
    command: ["redis-server", "--port 7777", "--appendonly yes", "--notify-keyspace-events", "Ex"]
    volumes:
    - ./data/redis:/data
    tmpfs:
    - /tmp
    - /var/run
    - /run
```


`podman-compose` have multiple mapping modes
the default one `1podfw` and alike (`1pod`, `hostnet`, `cntnet`, and `publishall`)
the end result would be that all containers would share same network namespace
resulting that you can listen to the same port (because it's same port on same namespace)

the only one mode that does not have this problem is `identity` (which does not do any change, it actually run multiple containers each in it's own network namespace),
but for that to work rootless (which is the objective of this project),
that's why I did not implement it (if you want to use `sudo podman-compose` then tell me I might give it a priority)

the actual reason why rootless containers can't talk to each other is not related to `podman-compose`
but it's related to [slirp4netns](https://github.com/rootless-containers/slirp4netns)

podman uses cni to configure network.

if there is a way to do it in `slirp4netns` or `cni` or if there is a way , or if you created an issue there ping me and reopen this issue.

please close this issue if I answered your question
