### ISSUE TITLE
Inconsistant volume directory naming convention with Docker-compose

### ISSUE THREAD

**Issue by xcffl** [muayyad-alsadi/podman-compose#27]
Docker-compose names volumes to the names start with pod name. For instance, a NextCloud docker-compose YAML
````yaml
version: '3'

volumes:
  db:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
````
should create a volume named `nextcloud_db` instead of `db` (current result), which is similar to the container names. The current result gives some confusion.

Note: this problem is only related to volumes instead of bind-mount.

**Comment by xcffl** [comment]
Plus, if volume names are defined behind services, they will not take effect.

**Comment by muayyad-alsadi** [comment]
Thank you for reporting this. I get your first point. But would you tell me more about the second comment.

> Plus, if volume names are defined behind services, they will not take effect.

**Comment by xcffl** [comment]
For instance, if a compose file is:
```yaml
version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql


volumes:
  db:
````
the `db` volume will not be named as `db` or `nextcloud_db`. It will be given a hash as its name.
