### ISSUE TITLE
[bug] Mistakes in processing commands

### ISSUE THREAD

**Issue by xcffl** [muayyad-alsadi/podman-compose#28]
When there are several commands under the `command` option, which is valid in docker-compose's world, podman-compose treat the later commands as the first one's value.

Here is an example:
````
➜  cat docker-compose.yml 
version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW

➜ podman-compose.py -t 1podfw -f docker-compose.yml up
➜ podman logs nextcloud-test_db_1
ERROR: mysqld failed while attempting to check config
command was: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW --verbose --help --log-bin-index=/tmp/tmp.FKTmfwEDrA"
````

However,
````
➜  cat docker-compose.yml 
version: '3'

services:
  db:
    image: mariadb
    command: ["--transaction-isolation=READ-COMMITTED", "--binlog-format=ROW"]

````
gives the right output.
