### ISSUE TITLE
support for build

### ISSUE THREAD

**Issue by muayyad-alsadi** [muayyad-alsadi/podman-compose#6]
the following example

https://github.com/mzazon/php-apache-mysql-containerized

does not yet work because it has build

more information can be found here

https://docs.docker.com/compose/compose-file/#build

```
version: '3'
services:
  webapp:
    build: ./dir
```
